apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
 name: aecio-ack-lambda-hello-word
 namespace: default
 annotations:
   services.k8s.aws/region: CHANGE_HERE
spec:
 name: aecio-ack-lambda-hello-word
 packageType: Image
 code:
     imageURI: CHANGE_HERE.dkr.ecr.CHANGE_HERE.amazonaws.com/aecio-ack-lambda-hello-word:latest
 role: arn:aws:iam::CHANGE_HERE:role/aecio-ack-lambda-hello-word
 description: function created by ACK lambda-controller e2e tests
 environment:
  variables:
    NAME: "ISAAC"
    SURNAME: "GUI2024"
    CONFIA: "YES"
    AUTHOR: "AECIO"
 tags:
    poc: "true"
